bombela/backward-cpp

backward.hpp

At my company we have CentOS 5 (old, I know) and `backward.hpp` had a problem with the `psiginfo()` function.
I'm testing for the availability of it as stated in the linux man pages: http://linux.die.net/man/3/psiginfo

Compilers with GLIBC < 2.10 don't have the psiginfo() function

---

README.md

The name of the class to obtain a stacktrace is called `StackTrace`, but the README examples use `Stacktrace`. If you hastily copy-paste the code found there, you'll be left wondering why it doesn't compile. :P 
This pull request fixes the typos.

Fix typos in README code examples

---

backward.hpp

This change renames two variables named "signals" to "unix_signals".
This is needed because Qt defines a macro "signals" that expands to nothing and is used by Qt's meta object compiler (which is kind of a C++ pre-processor) to add its [signal-slot feature](http://doc.qt.io/qt-5/signalsandslots.html). This will cause compilation of backward.hpp to fail, when used from a Qt application, because the variable "signals" will be expanded to "" by the cpp pre processor.
I'm trying to use backward-cpp in a Qt application, but so far it only works, if I include it using:
```C++
#pragma push_macro("signals")
#undef signals
#include <3rdparty/backward-cpp/backward.hpp>
#pragma pop_macro("signals")
```

Fix compatibility to Qt applications

---

BackwardMacros.cmake
CMakeLists.txt

This commit seperates some of the CMake code into a
BackwardMacros.cmake file. Including the CMakeLists.txt with
add_subdirectory doesn't work, because the variables it defines won't
be available from the including CMakeLists. With a .cmake file, they
will.
This change is backward-compatible, because CMakeLists.txt includes
the BackwardMacros.cmake as well.

Split off cmake macros and dependency detection to BackwardMacros.cmake

---

backward.hpp

On ArchLinux at least the bfd.h header errors out early if
PACKAGE or PACKAGE_VERSION have not been set. This patch
makes backward.hpp compile on this platform for me.

Define PACKAGE and PACKAGE_VERSION before including bfd.h

---

BackwardMacros.cmake

Hello,
Uppon modification of my CMakeLists my IDE (Clion) recall cmake on the same build dir, that uses the cache and append again the definitions to BACKWARD_DEFINITIONS.
It didn't generate build errors, but as the list of definition is dumped in BackwardMacros.cmake, I was curious.
Bye,
JB.

Don't append definitions if already cached

---

backward.hpp

When the stack trace is used directly (and not by a signal),
one may want to hide some of the first stack items because
they will always be the same calls.

Make StackTraceImpl*::skip_n_firsts() setter public

---

conanfile.py

It seems that the latest conan release changed the layout of the package options, so map syntax no longer works (Or it never had to be working and was my fault...).
I kept the revert commit in the history to make clear when I received and applied the conan.io feedback (Thanks @memsharded!).

Fix conanfile recipe

---

backward.hpp

Operator names are not supported by MSVC out of the box. Using them breaks code that needs to build with MSVC and/or (thus) uses "-fno-operator-names". As a header-only library should pursue maximal
portability, this PR replaces the single usage of operator names with the more portable operator syntax.

Don't use `and` for `&&`.

---

backward.hpp
test/test.hpp

The standard warnings of g++ 7.0.1 includes -Wimplicit-fallthrough.
The case of these warnings are fixed.
Enabling -Wshadow reveals further warnings that are fixed in this PR.

Fix g++ 7.0.1 warnings

---

backward.hpp

Sometimes it is necessary to write the stack trace to
a stream (for example, an std::stringstream) instead
of a file (for example, if you want to output the stack trace
later, for a testing framework, or for a special kind of
exceptions with stack trace information).
This pull request makes the Printer (and Colorizer)
write to streams. For the Printer, backward-compatibility
is kept since all public print() methods use the
stream-based ones now.
For the Colorizer, this is a compatibility-breaking change.

Print to streams

---

backward.hpp

While compiling with g++ 7, I get the following warning:
``` cpp
backward.hpp: In constructor ‘backward::cfile_streambuf::cfile_streambuf(FILE*)’:
backward.hpp:1677:29: warning: declaration of ‘sink’ shadows a member of ‘backward::cfile_streambuf’ [-Wshadow]
cfile_streambuf(FILE *sink): sink(sink) {}
^
backward.hpp:1701:8: note: shadowed declaration is here
FILE *sink;
^~~~
```
And this PR removes that.

Remove gcc-7 -Wshadow warning

---

backward.hpp

for ip==0, we sometimes calculate ip-=1.
ip is unsigned, so this is an underflow.
This is not strictly an UB, but more pedantic sanitizers
do catch this and report as possible error.
So why not instead just explicitly set value 0xffff...
(result of 0-1) and avoid this warnings.

To pass sanitization, do not rely on underflow 0-1

---

backward.hpp

As discussed in comments of #63 , it can happen that we reach frame with ip==0, shown as "[0xffffffffffffffff]",
when using this library as documented and iterating entire backtrace up to "i<st.size()"
This situation causes a memory error (reading 1 position behind end of string), that was catched by valgrind.
This patch resolves it.

fix off-by-one when resolve goes up to ip==0 frame

---

backward.hpp
test/suicide.cpp

*Read the pc as specified for aarch64 processors.
*Disable division by zero tests, since aarch64 does not trap these and
therefore does not generate SIGFPEs there.
*All other tests succeed.

Add aarch64 support

---

BackwardConfig.cmake

On some distributions, libbfd is only available as static library. E.g.
on OpenSuse Leap 42.2, there are these two files:
libbfd.a
libbfd-2.28-system.so
backward-cpp, when attempting to link to bfd, will select the static
library and fail b/c there are undefined references to symbols from
libiberty/libz:
```
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/libbfd.a(elflink.o):
In function `elf_link_add_object_symbols':
/home/abuild/rpmbuild/BUILD/binutils-2.26.1/build-dir/bfd/../../bfd/elflink.c:4733:
undefined reference to `objalloc_free_block'
/home/abuild/rpmbuild/BUILD/binutils-2.26.1/build-dir/bfd/../../bfd/elflink.c:5027:
undefined reference to `_sch_istable'
...
```
After this patch we also link against the direct dependencies of libbfd.a, namely libiberty and libz
Also see: …

backward-cpp: Make sure to properly link against bfd.a

---

backward.hpp

In our code, we need to take certain cleanup actions
after receiving a SIGSEGV. This makes it difficult to
integrate with backward, as our custom sighandler is overriden.
A simple solution is to have backward-cpp expose the
core sighandling logic as a public function, which
we can simply call from within our code. This is not
currently possible since sig_handler is private, and
additionally raises the signal again at the end.
This pull request makes the above possible. The alternative
is to copy handleSignal into our own code, which is just ugly.

Allow running sighandler logic as part of a cleanup chain

---

BackwardConfig.cmake

replace _BACKWARD_INCLUDE_DIRS by BACKWARD_INCLUDE_DIRS to fix issue #82

cmake macro add_backward erroneously expanded

---

.travis.yml
conanfile.py
test_package/CMakeLists.txt
test_package/conanfile.py

See #90.
Basically, the conan recipes and the build commands used by the CI were outdated (the conan team seem to have been working so hard these last months, releasing like rabbits :P)

Update conan recipes to use the latest recipe APIs. Fixes #90

---

CMakeLists.txt

Modify top-level CMakeLists.txt to
- check if compiler is nvcc/nvcc_wrapper
- if nvcc_wrapper detected, trigger off cxx gnu extensions and pedantic error flags

make backward-cpp compatible with nvcc_wrapper compiler wrapper

---

backward.hpp

GCC shows warnings like:
`warning: 'virtual std::streamsize backward::cfile_streambuf::xsputn(const char_type*, std::streamsize)' can be marked override [-Wsuggest-override] `
In the cfile_streambuf class. This patch #defines override to be nothingness in C++98 and adds the override keyword to the functions with the warnings.

Remove override warnings in C++11 builds

---

backward.hpp

Some compiler flags and/or compilers will set this instead. There are
undoubtedly others but I know this fixes my problem.
The flag that I'm currently seeing alter this is `-std=c++0x`.
Signed-off-by: Christy Norman <christy@linux.vnet.ibm.com>

add check for __linux__

---

backward.hpp

On some platforms we got a warning about 'info' not being used because the `#if _XOPEN_SOURCE >= 700 || _POSIX_C_SOURCE >= 200809L` was not true. Can't remember which platform right now but this patch addressed it.

Remove warning about unused variable 'info"

---

BackwardConfig.cmake

Debian installs `libdwarf.h` at `/usr/include/libdwarf/`. This change enables cmake finding this header on [debian](https://packages.debian.org/stretch/amd64/libdwarf-dev/filelist).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bombela/backward-cpp/111)

Find libdwarf.h on debian

---

BackwardConfig.cmake

This allows using each definition (resulting from `BackwardConfig.cmake`) separately, e.g., in conjunction with cmake's `configure_file()` command and thus can be defined in a cmake-generated source file before a build.
Example:
`Config.h.in`
```cmake
#cmakedefine01 BACKWARD_HAS_UNWIND
#cmakedefine01 BACKWARD_HAS_BACKTRACE
#cmakedefine01 BACKWARD_HAS_BACKTRACE_SYMBOL
#cmakedefine01 BACKWARD_HAS_DW
#cmakedefine01 BACKWARD_HAS_BFD
#cmakedefine01 BACKWARD_HAS_DWARF
```
`CMakeLists.txt`:
```cmake
include(BackwardConfig)
configure_file( "${PROJECT_SOURCE_DIR}/Config.h.in"
"${PROJECT_BINARY_DIR}/Config.h" )
```
`SomeProjectFile.C`:
```cpp
#include "Config.h"      // generated by cmake based on Config.h.in
#include "backward.hpp"  // backward-cpp now configured based on BackwardConfig.cmake …
```

Export each definition individually

---

BackwardConfig.cmake

Without this they are not correctly included in BACKWARD_LIBRARIES even when they are found.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bombela/backward-cpp/110)

Make cmake append libs dwarf and elf

---

backward.hpp

This change replaces old-style casts with `static_cast` and `reinterpret_cast` as needed to avoid compilation warnings.

Fix -Wold-style-cast compilation warnings

---

backward.hpp

Improve how CU DIEs are iterated by only processing those whose tag is DW_TAG_compile_unit. Reset (ie, advance to the end) libdwarf's CU iterator only if we found a CU as, if not, we will be already be at the end.

Code optimizations

---

CMakeLists.txt

The comon practice in cmake to allow to specify the libdir or
includedir using GNUInstallDirs which introduces the following
options:
* CMAKE_INSTALL_INCLUDEDIR
* CMAKE_INSTALL_LIBDIR
The main motivation behind this change is ability to use /usr/lib64
instead of /usr/lib as a libdir.

cmake: Use GNUInstallDirs for libdir and includedir

---

backward.hpp

Check if the compiler is clang before using clang only pragma statements.

Fix unknown pragma warning in gcc

---

backward.hpp

Returning a `const T` as opposed to `const T&` serves little purpose and 
is most likely not what the writer intended.
This was called out by clang-tidy.

Add missing ref qualifier

---

backward.hpp
test/_test_main.cpp

Linux is not synonymous with glibc.  Alpine linux (among others) uses
libmusl as the standard C library.  Alpine/libmusl doesn't have
backtrace, dladdr1, execinfo.h or error.h.  It does have libunwind
and program_invocation_name and libdwarf and libelf are available as
packages.
This patch makes backward-cpp work on Alpine linux (and hopefully
others that rely on libmusl).
This patch makes dladdr1 dependent on the __GLIBC__ pp-symbol
(rather than __ANDROID__).
It uses __has_include (protected by a defined()) rather than __APPLE__
to decide whether to include <error.h> in _test_main.cpp.

Improve portability to non-glibc Linux systems

---

backward.hpp
test/suicide.cpp

MIPS didn't export regs at mcontext_t so we need to cast it as sigcontext.
All test passed on my mips64el machine.

Add mips support

---

backward.hpp

The current code leaks memory when __cxa_demangle reallocs (which you can easily check under asan or valgrind). This fixes the leak.

fix a memory leak when __cxa_demangle reallocs

---

backward.hpp

I can't even compile backward-cpp without this fix.

fix bad pointer comparison in libdwarf backend

---

backward.hpp

This is useful for binaries (using backward-cpp) that are built with
relative source file paths.  In such a situation, backward-cpp will
generally not be able to locate the source files.  This change allows
the user to specify a delimited list of search paths in the following
environment variable:
```
BACKWARD_CXX_SOURCE_PREFIXES
```
The paths are separated by semicolons on Windows and colons otherwise.
When the environment variable is set, those search paths will be tried
first.  If they do not yield any valid files then backward-cpp will
fall back to current behavior.
Fixes #153

Allow specifying list of source file search paths in environment var

---

backward.hpp

Older libstdc++ versions (e.g. 4.8.2) don't have the rvalue overload of `std::getline`. This fixes this error when compiled with libstdc++ 4.8.2:
```
ext/backward-cpp/backward.hpp: In static member function 'static std::string backward::TraceResolverLinuxBase::get_argv0()':
ext/backward-cpp/backward.hpp:1031:66: error: no matching function for call to 'getline(std::ifstream, std::string&, char)'
std::getline(std::ifstream("/proc/self/cmdline"), argv0, '\0');
^
ext/backward-cpp/backward.hpp:1031:66: note: candidates are:
/usr/include/c++/4.8/bits/basic_string.h:2799:5: note: std::basic_istream<_CharT, _Traits>& std::getline(std::basic_istream<_CharT, _Traits>&, std::basic_string<_CharT, _Traits, _Alloc>&, _CharT) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = …
```

Call `std::getline` with an lvalue `std::ifstream` rather than an rvalue

---

backward.hpp

* For macro changes at https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=fd3619828e94a24a92cddec42cbc0ab33352eeb4
Based on patch by Leo at https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/cloudi/fix-new-binutils.patch

Fix for binutils 2.34

---

backward.hpp

Testing clang++ 5.0 and g++ 4.8.4 both required tweaking the template syntax to avoid `>>` (https://en.wikipedia.org/wiki/C%2B%2B11#Right_angle_bracket).  It is required for compatibility with older C++ compilers.

Fix for C++ compilers without C++11

---

backward.hpp

this will cause super-mega long loop (from ~max size_t till 0)

Underflow in size() if stacktrace is smaller than skip_n_firsts()

---

backward.hpp

If we fall back to DWARF processing trying to find a function name we deallocated the wrong object because of a copy/paste error. This part of the code was hit only very rarely, which made this bug undetected for a long time.

Fix rare crash when looking for a function name

---

backward.hpp

Fix memory leak that was introduced by a coding mistake
in an earlier attempt to fix a leak on realloc:
dd8af25 fix a memory leak when __cxa_demangle reallocs
The value of _empty was accidentally negated.
Closes #171

fix memory leak from demangle

---

BackwardConfig.cmake
README.md
backward.cpp
backward.hpp

libunwind interprets the signal handler frame and provides better stacktraces. Because it lets us inspect the stack we can manipulate it to unwind across bad function dereferences.
Clang in macOS provides an API compatible version of libunwind, so there's no need to link against any library.
Added a new function to pass the signal handler context and error address to the backward object (unused in the BFD and elfutils implementations).
Added the documentation for the new unwinder to the README file.
In order to not introduce a new default CMake still prefers gcc's unwind over libunwind. I have a patch for automatic detection of the available unwinders and can commit it if making AUTO the default is desired.

Added libunwind support to Linux and macOS

---

backward.hpp

According to the DWARF spec, DW_AT_call_file is an unsigned value and we were treating it like a signed integer. Some old gcc compilers for ARM create, probably because of a bug, very high file index numbers which were being interpreted as a negative number, causing a crash.

DW_AT_call_file is an unsigned value

---

backward.hpp

Fixes #200.
When compiling on Apple Silicon at commit `27a8900`, the following build error is produced:
```
In file included from ../backward-cpp/backward.cpp:36:
../backward-cpp/backward.hpp:4160:60: error: member reference type 'struct __darwin_mcontext64 *' is a pointer; did you mean to use '->'?
error_addr = reinterpret_cast<void *>(uctx->uc_mcontext.pc);
~~~~~~~~~~~~~~~~~^
->
../backward-cpp/backward.hpp:4160:61: error: no member named 'pc' in '__darwin_mcontext64'
error_addr = reinterpret_cast<void *>(uctx->uc_mcontext.pc);
~~~~~~~~~~~~~~~~~ ^
```
This is caused by [`__aarch64__`](https://github.com/bombela/backward-cpp/blob/27a89004a86fe2a665f041c198c7fbab7489e278/backward.hpp#L4159) being defined on Apple Silicon, however is incorrect for assigning the error address.
A conditional …

Add support for Apple Silicon

---

backward.hpp

Fixes #198 
My limited testing showed that backward-cpp works fine without the deprecated `std::set_unexpected`. But I cannot guarantee that it would still work for all cases as I was not researching why `std::set_unexpected` was used by backward-cpp and why was it removed from c++17.

Fix compilation error with C++17 compiler

---

backward.hpp

TraceResolver has a load_stacktrace() method accepting only an
object like StackTrace. That object is basically an array of
pointers.
This was not really convenient, because
1) it required carrying of this StackTrace object from the moment
of its creation to the load_stacktrace() invocation. Sometimes
this is a long path. And that may break encapsulation, if a
project, using Backward, does not want to include Backward
header anywhere except for 1 or 2 C++ files, responsible for
collection and resolution of addresses. So basically,
load_stacktrace() prevented split of stack load and stack
resolution into separate submodules of a project;
2) that made impossible to use Backward to resolve a stack,
collected not via Backward.
The patch introduces a new method load_addresses(), accepting an …

Introduce TraceResolver::load_addresses() for raw address array

---

backward.hpp

Fixes:
```
In file included from 
backward-cpp/backward.hpp: In member function ‘virtual void backward::TraceResolverImplBase::load_addresses(void* const*, int)’:
bombela/backward-cpp/backward.hpp:1214:43: warning: unused parameter ‘addresses’ [-Wunused-parameter]
1214 |   virtual void load_addresses(void *const*addresses, int address_count) {
|                               ~~~~~~~~~~~~^~~~~~~~~
bombela/backward-cpp/backward.hpp:1214:58: warning: unused parameter ‘address_count’ [-Wunused-parameter]
1214 |   virtual void load_addresses(void *const*addresses, int address_count) {
|                                                      ~~~~^~~~~~~~~~~~~
```

Fix unushed parameter warnings

---

backward.hpp

Fixes some warnings:
```
... bombela/backward-cpp/backward.hpp:1210:7: warning: ‘class backward::TraceResolverImplBase’ has virtual functions and accessible non-virtual destructor [-Wnon-virtual-dtor]
1210 | class TraceResolverImplBase {
|       ^~~~~~~~~~~~~~~~~~~~~
... bombela/backward-cpp/backward.hpp:1243:7: warning: base class ‘class backward::TraceResolverImplBase’ has accessible non-virtual destructor [-Wnon-virtual-dtor]
1243 | class TraceResolverLinuxBase : public TraceResolverImplBase {
|       ^~~~~~~~~~~~~~~~~~~~~~
```
I considered using a `= default` virtual destructor, but I wasn't sure about backwards compatibility.

Add empty virtual destructor to TraceResolverImplBase base class

---

backward.hpp

This PR fixes compilation under Windows with Visual Studio 14 2015 Win64.
std::back_inserter() method replaces in <iterator> header file https://en.cppreference.com/w/cpp/iterator/back_inserter.
To fix it, the header file is included.

Fix compilation under Windows with Visual Studio 14 2015 Win64

---

backward.hpp

This MR fixes stack trace under Windows.
For example run `test_suicide` test.
Stack trace
Before:
```
-- running test case: stackoverflow
Stack trace (most recent call last):
#10   Object "", at 00007FFCC4777C24, in BaseThreadInitThunk
#9    Object "", at 00007FFC9BC4542C, in register_onexit_function
#8    Source "c:\program files (x86)\microsoft visual studio 14.0\vc\include\thr\xthread", line 210, in std::_Pad::_Call_func [00007FF62002065D]
207:    static _Call_func_ret _STDCALL _Call_func(void *_Data)
208:            {       // entry point for new thread
209:            static_cast<_Pad *>(_Data)->_Go();
> 210:            _Cnd_do_broadcast_at_thread_exit();
211:            return (0);
212:            }
#7    Source "c:\program files (x86)\microsoft visual studio …
```

Fix printing stack trace under Windows.

---

backward.hpp

It fails to compile on linux when BACKWARD_HAS_BACKTRACE is set because variable name in load_from function has a typo.

fix typo in variable name

---

backward.hpp

Resolves https://github.com/bombela/backward-cpp/issues/224.
Also, replace tabs with spaces in comment list lines to make list consistent.

Specify that variable values in stacktraces are not supported currently

---

backward.hpp

Fixes warning "format string is not a string literal (potentially insecure)" and a memory leak.

Don't pass buffer as format string and free buffer

---

test/suicide.cpp

The divide_by_zero is meant to run if both `__aarch64__` and `__mips__` are not defined, meaning that the test is being compiled on any other architecture. As it is now, the test is being compiled also on `__aarch64__` architecture, as `!defined(__mips__)` is true.

Fix tests on aarch64 and mips architecture

---

backward.hpp

This is extra important if the project uses `-Werror`.
Thie PR fixes warnings when compiling with `-Wundef` and `-Wold-style-cast`; i.e. projects which uses these and `-Werror` can properly compile with this PR.

Fix Compile Errors when used with certain GCC flags

---

BackwardConfig.cmake

I can change this as desired, if you want the original function to stay the same I can make a second `add_backward_as_system` function or something else; I did it this was to prevent code duplication going forward but I can edit this if you want something different.
The benefit of allowing include as system is that it allows gcc to ignore warnings generated from this code. For example, if compiling with `-Wall`, you get `W-sign-compare`, as shown [here](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html). Thus, compiling with `-Wall -Werror` may lead to a failure to compile since there are a few sign switches in this code, such as [here](https://github.com/bombela/backward-cpp/blob/4b8715b9081251947e3881098f65f8fa74c300aa/backward.hpp#L1957). By including as a system error, warnings …

Allow adding backward as system headers

---

backward.hpp

Requires using the Linux kernel header file ptrace.h.
Allows struct pt_regs to be used for accessing the
nip (Next Instruction Pointer) register value.
This fixes a compilation problem at https://github.com/bombela/backward-cpp/blob/872350775655ad610f66aea325c319950daa7c95/backward.hpp#L4225 on Alpine Linux.

Fix Linux powerpc use of struct pt_regs

---

BackwardConfig.cmake

BackwardConfig.cmake was not explicitly pulling in the dependencies of libdw (libelf, libz, libpthread, etc.), which made it fail to link when libdw was built as a static library (and therefore didn't explicitly encode those dependencies). This fixes that. For context, I'm trying to make it work with vcpkg, using its version of elfutils. (I'm working on adding a vcpkg port for this library, too.)
I had logic in here to use pkg-config, but doing it that way made it use the system version of libdw instead of the one in vcpkg.

Find dependencies for statically-linked libdw

---

backward.hpp

Compilation on MinGW 32bits is Failing with
```
[ 66%] Building CXX object CMakeFiles/backward.dir/backward.cpp.obj
In file included from C:/Users/runneradmin/AppData/Local/.xmake/cache/packages/2205/b/backward-cpp/v1.6/source/backward.cpp:36:
C:/Users/runneradmin/AppData/Local/.xmake/cache/packages/2205/b/backward-cpp/v1.6/source/backward.hpp:341:17: error: conflicting declaration 'typedef SSIZE_T ssize_t'
341 | typedef SSIZE_T ssize_t;
|                 ^~~~~~~
In file included from D:/a/_temp/msys64/mingw32/include/stdlib.h:9,
from D:/a/_temp/msys64/mingw32/include/c++/11.3.0/cstdlib:75,
from D:/a/_temp/msys64/mingw32/include/c++/11.3.0/bits/stl_algo.h:59,
from D:/a/_temp/msys64/mingw32/include/c++/11.3.0/algorithm:62,
from C:/Users/runneradmin/AppData/Local/.xmake/cache/packages/2205/b …
```

Fix compilation on mingw 32bits

---

backward.hpp

Refer to https://github.com/bombela/backward-cpp/issues/262

Fix Wold-style-cast warnings #262

---

backward.hpp

Explicitly cast `line` and `col` variabiles to `unsigned` to avoid `-Wsign-conversion` (warnings or errors if `-Werror` is enabled).
This avoids unnecessary wrapper header files around `backward.hpp` to ignore this type of warnings or disable the warning everywhere which could be unsafe in some cases.

Explicitly cast `line` and `col` variabiles to `unsigned`.

---

.gitignore
backward.hpp

Addresses issue #215.
Actually, by default is printing "in reverse" (top of the stack at the "bottom"), but with this change, you can also print it as the debugger would print it  (top of the stack at the "top").

support printing stack trace in reverse

---

backward.hpp

warning C4267: 'argument': conversion from 'size_t' to 'DWORD', possible loss of data

Add cast for warning C4267

---

backward.hpp

* Dl_info is required when BACKWARD_SYSTEM_LINUX is defined
(was a problem for BACKWARD_HAS_DW == 1)

Fix missing Dl_info type

---

backward.hpp

In release build without symbols and frame pointers, `_Unwind_Backtrace` can be a no-op, not invoking the callback even a single time.
This then keeps the `_index` at `-1`, so after casting into `size_t` and attempting to allocate vector with that size, app crashes (vector::resize to MAX_UINT does not work 😛 ).
The issue didn't happen when using the `backtrace` backends - it correctly returns the empty stack trace in that case.
This patch ensures the same behavior also when using `unwind`.

don't crash when `_Unwind_Backtrace` fails

---

test/suicide.cpp

Both architectures do not trap on division by zero

Fix tests on PowerPC and RISC-V

---

backward.hpp

This can be useful when the library loads before the file paths are known.
For example, if this is being used in a library and the path information is only known by the parent process; without this the library would (by default) before main, before the main process could give this information.
In my use case, this is part of a native module to another programming language, the module is loaded when the native program loads, however, so the program does not have any time to inform backward of where the files.

Allow adding to the file prefix list taken from the env

---

backward.hpp

In fact, I was build with NDK r21e, which didn't provide `execinfo.h`.
So I set `BACKWARD_SYSTEM_UNKNOWN=1` to build.
I use backward-cpp to tack stacktrace, compiler complain
```
backward.hpp:1236:23: error: no member named 'begin' in 'backward::StackTrace'
load_addresses(st.begin(), static_cast<int>(st.size()));
backward.hpp:4056:15: note: in instantiation of function template specialization 'backward::TraceResolverImplBase::load_stackt
race<backward::StackTrace>' requested here
_resolver.load_stacktrace(st);
backward.hpp:4017:5: note: in instantiation of function template specialization 'backward::Printer::print_stacktrace<backward:
:StackTrace>' requested here
print_stacktrace(st, os, colorize);
```
So I add this api into `StackTraceImpl`

Support Unknown System build with `BACKWARD_SYSTEM_UNKNOWN=1` in user take stack trace case.

---

BackwardConfig.cmake

if support "-gcodeview" add  `-gcodeview`, `-Wl,--pdb=`
I found this solution here https://github.com/bombela/backward-cpp/issues/176#issuecomment-1382442652
if compiler don't support `-gcodeview` is old version with `msvcr90`

Fix for mingw, if support "-gcodeview" add -gcodeview

---

BackwardConfig.cmake

To bring some context, I tried to build `backward-cpp` for [SerenityOS](https://github.com/SerenityOS/serenity).
We only rely on binutils' Makefile which doesn't generate a `.so` for `libbfd`. When building `backward-cpp` with this configuration, I faced linker errors with symbols from `sframe`. It appears that `sframe` is also a dependency of `libbfd`.
FWIW, it's in phase with what [Arch](https://github.com/archlinux/svntogit-packages/blob/1f454232f6f0d227dd5b4b1eee6b7fc2b4a42fd4/trunk/PKGBUILD#L115) do to package `libbfd.so`:
"echo 'INPUT( /usr/lib/libbfd.a -lsframe -liberty -lz -lzstd -ldl )' > "$pkgdir/usr/lib/libbfd.so""

Add `sframe` to libbfd's dependencies list

---

BackwardConfig.cmake
CMakeLists.txt
README.md

This PR should make it easier to use the `backward.cpp` file in downstream projects. As documented in the README, with this PR there are now three targets:
- `Backward::Interface` is an interface target that brings compiler definition
flags, include directory, and external libraries. This is all you need to use
the `backward.hpp` header library.
- `Backward::Object` brings `Backward::Interface` and `backward.cpp` as an
`OBJECT` CMake library. This target cannot be exported, so it is not
available when Backward is used via `find_package`.
- `Backward::Backward` brings `Backward::Interface` and `backward.cpp` as
either `STATIC` or `SHARED` library (depending on the `BACKWARD_SHARED`
option). This target is exported and always available, however note that the
linker will not include unused …

CMake modernization: add Backward::Interface and Backward::Object targets

---

CMakeLists.txt

When building with CMake version 3.27.2 I received this error:
```
CMake Deprecation Error at build/gcc/_deps/backward-src/CMakeLists.txt:23 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```

Update depreciated CMake version

---

backward.hpp

This fix covers 10.5–10.6. (For 10.4 `ss.srr0` should be used instead of `__ss.__srr0`, but I assume it is unneeded to complicate the code for that sake.)
P. S. I have been pointed out to the original code from here: https://github.com/d99kris/heapusage/pull/17

backward.hpp: fix for macOS PowerPC

---

backward.hpp

test pass with gcc on loongarch64:
```
tsingkong@debian:/data/github/backward-cpp$ ./builds.sh test
make: 进入目录“/data/github/backward-cpp/build_c++98_gcc”
Running tests...
Test project /data/github/backward-cpp/build_c++98_gcc
Start 1: test
1/5 Test #1: test .............................   Passed    0.38 sec
Start 2: stacktrace
2/5 Test #2: stacktrace .......................   Passed    0.00 sec
Start 3: rectrace
3/5 Test #3: rectrace .........................   Passed    0.00 sec
Start 4: select_signals
4/5 Test #4: select_signals ...................   Passed    0.26 sec
Start 5: suicide
5/5 Test #5: suicide ..........................   Passed    0.81 sec
100% tests passed, 0 tests failed out of 5
Total Test time (real) =   1.47 sec
make: 离开目录“/data/github/backward-cpp/build_c++98_gcc” …
```

add support for loongarch
